### ISSUE TITLE
Owin hosting non standard port and bad mac

### ISSUE THREAD

**Issue by suddenelfilio** [pcibraro/hawknet#21]
I know you already noticed this yourself. When you use owin hosting the authentication fails because the port is not set correctly you can see this when the normalized string is printed in the trace. 

Is there any update or workaround? maybe force a configurable value?

**Comment by BrannonKing** [comment]
Is this still an issue?

**Comment by BrannonKing** [comment]
I filed an issue: https://katanaproject.codeplex.com/workitem/400

**Comment by BrannonKing** [comment]
It ends up that the issue is with the HawkNet library. I found it and put in a pull request: https://github.com/pcibraro/hawknet/pull/28 . The `HawkClientMessageHandler.SendAsync` override has this line: `request.Headers.Host = request.RequestUri.Host;`. That line is wrong; it needs the port. The `OwinRequest.Host` property includes the port but the `Uri.Host` does not; I can see where it would get confusing. The `SignRequest` method actually gets it right when the header is absent, so I just removed that header setter to fix the issue. Setting the Host header from the client doesn't seem quite right anyhow.

**Comment by pcibraro** [comment]
Awesome. Thanks for working on this. I will apply your pull request

**Comment by pcibraro** [comment]
I just pushed the updated version of the nuget package. Thanks

**Comment by BrannonKing** [comment]
I see that the HawkNet.Owin package was renewed today. However, wasn't this fix in the HawkNet.WebApi package?

**Comment by pcibraro** [comment]
Yes. Let me release that package as well

**Comment by BrannonKing** [comment]
Any ETA on releasing the WebApi package? Thanks for your time on this.

**Comment by pcibraro** [comment]
I just pushed it. Sorry it took so long. Thanks

**Comment by BrannonKing** [comment]
It's working well. Thank you.
